### ISSUE TITLE
I help u

### ISSUE THREAD

**Issue by EvilDevil7** [MakerbakerYT/CrypticFactions#1]
i like what you are doing i can help you

**Comment by MakerbakerYT** [comment]
Do You know how to code?

**Comment by EvilDevil7** [comment]
Yes, I know a little bit

**Comment by MakerbakerYT** [comment]
ok i added uu

**Comment by EvilDevil7** [comment]
ok well i would like to check the ranks well to make a little configuration
to the format

**Comment by MakerbakerYT** [comment]
Okie Do What you can do

**Comment by EvilDevil7** [comment]
Ok u have discord or server

**Comment by MakerbakerYT** [comment]
im makeing a server also u want my user for discord
its MakerbakerYT#3139

**Comment by EvilDevil7** [comment]
If you want I can help you on your server so by discord we can talk and
work better

**Comment by MakerbakerYT** [comment]
Ight
Just add me as a friend and send me a link to your server
